version: '3.3'
services:
    hljs-server:
        volumes:
            - '/var/run/sfss:/tmp/sfss'
        image: hljs-server
    sfss:
        ports:
            - '8000:8000'
        volumes:
            - '/var/sfss:/var/sfss'
            - '/var/run/sfss:/tmp/sfss'
        environment:
            - 'ROCKET_ADDRESS=127.0.0.1'
            - 'SFSS_LOCATION=/var/sfss'
            - 'SFSS_TITLE=NyxShare'
            - 'SFSS_LABEL=Choose file...'
            - 'SFSS_ROOT='
            - 'SFSS_URL=https://share.nyx.xyz'
        image: sfss
